name: Welcome
description: Welcomes new users.
author: bubkoo <bubkoo.wy@gmail.com>
inputs:
  GITHUB_TOKEN:
    description: 'Your GitHub token for authentication'
    required: true
  FIRST_ISSUE:
    description: Comment to be posted to on first time issues.
  FIRST_PR:
    description: Comment to be posted to on PRs from first time contributors in your repository.
  FIRST_PR_MERGED:
    description: Comment to be posted to on pull requests merged by a first time user.
runs:
  using: docker
  image: Dockerfile
branding:
  color: coral
  icon: heart
